{% set version = "0.30.0" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 3b90407dbfba7c26c44da2665ac5526b24c877fe7b56303b53714609e35edbc6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.5
  run:
    - ipykernel >5.5.6
    - jedi >=0.18
    - jupyter_core >=4.9.2
    - pexpect >=4.8
    - python >=3.7
    # extras
    - ipyparallel
    - portalocker

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Metakernel for Jupyter.

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
