{% set version = "0.29.3" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 26f93a7d07c2c2e00b1a33539f8582bd4649856c3eac28fedec105d24482f6c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.5
  run:
    - ipykernel >5.5.6
    - jedi >=0.18
    - jupyter_core >=4.9.2
    - pexpect >=4.8
    - python >=3.7
    # extras
    - ipyparallel
    - portalocker

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Metakernel for Jupyter.

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
