{% set version = "0.30.2" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: 4a27dfd853b849f0128242c55204ee597a5a8d864294f26084baf2fbc814d5a4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.5
  run:
    - ipykernel >5.5.6
    - jedi >=0.18
    - jupyter_core >=4.9.2
    - pexpect >=4.8
    - python >={{ python_min }}
    # extras
    - ipyparallel
    - portalocker

test:
  requires:
    - python {{ python_min }}
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.magics.tests
    - metakernel.tests
    - metakernel.utils

about:
  home: https://github.com/Calysto/metakernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Metakernel for Jupyter.

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
