{% set version = "0.31.0" %}

package:
  name: metakernel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/metakernel/metakernel-{{ version }}.tar.gz
  sha256: eeb6cbd357925709cb2b390a78d9b503a1267b48c13c0bf4eaf0d51068526e3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.5
  run:
    - ipykernel >5.5.6
    - jedi >=0.18
    - jupyter_core >=4.9.2
    - pexpect >=4.8
    - python >={{ python_min }}
    # extras
    - ipyparallel
    - portalocker

test:
  imports:
    - metakernel
    - metakernel.magics
    - metakernel.utils
  commands:
    - pip check

about:
  home: https://github.com/Calysto/metakernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Metakernel for Jupyter.

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
