travis:
  secure:
    BINSTAR_TOKEN: AS3ECPQsOTrZU6kZFfACySDQwhZ6pZQdx+qIxNHJdBWT4HbzHL3ZmqWxScoQCRczENYr1GkQU6XK/kRd5OjRfwWtzPGLZAFmTrVOYlqBKt+vm8nqYoETf15gzx7ygC/58npiVgpNeBTB4wT87pcrzdCueR+DVEUUUm7bsE4JT648VK6ZpX0rUuFX7zzwTHcMc43Z4IsSUJy7mat28lFvt5gYmUaPZEv1UmVqLXklFm+yhmU9am5OQ8X8BtorQmFp4emMKYJIlbuW2BbDlk7/QrWYCRVTov1sWUNNNBMTylr7z8Gfv3tFhRMrVWVvOuH2PSfG6KQbde/21XjiiCIty9k6ES18yLio2olK8mDFNy2HUDtIjDDiaVcnnxAQRECzbQV4U+hcxOqGB67QYCywulZGqht8tPWqV44NCuB1h2ul7UdnAZZ6xCiP87BOxhGfihGlFM9pkbqf0AQPRFwkZ7kQTCyvX4jYsJ6iaiYMv9iKEJaAt6Jx42yM8n3t+k5uSXbtCucfvdsRnqaqAzRt8EtWq6OyhFLYoPpS3PKAJeaFr+PIK7lMi6Atah4BpsO3iKB1gDTmqN8TNK3h19eLAjOBC23hPBmk/TUHTHOS2o5YxYlxa01YcVNLv8IsEKykZz64kCUrKbgCyqRly4SezQlcoRn24S1aKx56XO4V7IM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
